spring:
  application:
    name: testapi
  datasource:
    url: jdbc:postgresql://localhost:5432/test_java_api
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

token:
  signing:
    key: testko34krok430c12ioi
