services:
    platform_service:
        build: ./PlatformService
        container_name: platform_service
        ports:
            - "8080:8080"
        depends_on:
            - postgresql
            - rabbitmq
        networks:
            - app_net
        environment:
            - db_host=postgresql
            - db_name=platform_db
            - rabbit_hostname=rabbitmq
        volumes:
            - ./PlatformService/build:/app
    postgresql:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=platform_db
        ports:
            - "5432:5432"
        networks:
            - app_net
    rabbitmq:
        image: rabbitmq:3.10.7-management
        hostname: rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"
        

networks:
    app_net:
        driver: bridge
