spring:
  application:
    name: ai_service
  datasource:
    url: jdbc:postgresql://${db_host}:5432/${db_name}
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true

rabbitmq:
  hostname: ${rabbit_hostname}
server:
  port: 8081